name: Run Lint and Test

on:
  push:
    branches-ignore: 'main'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test
