name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR tile
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          add_label: 'true'
          task_types: '["feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"]'
