name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          add_label: 'true'
          task_types: '["feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"]'
          custom_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "style": "style", "refactor": "refactor", "perf": "performance", "test": "testing", "build": "build", "ci": "CI/CD", "chore": "chore", "revert": "revert"}'
